apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-frontend
  labels:
    app: ledger-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-frontend
  template:
    metadata:
      labels:
        app: ledger-frontend
    spec:
      containers:
        - name: ledger-frontend
          image: ledger-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ledger-frontend
spec:
  type: NodePort
  selector:
    app: ledger-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30006
