services:
  postgres:
    image: postgres:16
    container_name: user-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - ledger-net

  simple-auth:
    image: simple-auth
    container_name: simple-auth
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: SimpleAuth/SimpleAuth.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://0.0.0.0:5001"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=simpleauth;Username=postgres;Password=postgres"
    ports:
      - "5001:5001"
    networks:
      - ledger-net

  user-api:
    image: user-api
    container_name: user-api
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: UserApi/UserApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:5002
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=userdb;Username=postgres;Password=postgres"
    ports:
      - "5002:5002"
    networks:
      - ledger-net

  financial-service:
    image: financial-service
    container_name: financial-service
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: FinancialService/FinancialService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:5003
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=financialservice;Username=postgres;Password=postgres"
    ports:
      - "5003:5003"
    networks:
      - ledger-net

  ledger-gateway:
    image: ledger-gateway
    container_name: ledger-gateway
    build:
      context: .
      dockerfile: LedgerGateway/LedgerGateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:5000
    ports:
      - "5000:5000"
    networks:
      - ledger-net

volumes:
  user-data:

networks:
  ledger-net: