services:
  postgres:
    image: postgres:16
    container_name: user-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - ledger-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  event-relay-worker:
    container_name: event-relay-worker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health/ready"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    depends_on:
      broker:
        condition: service_healthy
    build:
      context: .
      dockerfile: EventRelayWorker/Dockerfile
    env_file:
      - ./env/event-relay-worker.env
    networks:
      - ledger-net

  simple-auth:
    image: simple-auth
    container_name: simple-auth
    depends_on:
      - simple-auth-migrations
    build:
      context: .
      dockerfile: SimpleAuth/SimpleAuth.Api/Dockerfile
    environment:
      OpenTelemetry__ExporterUrl: http://signoz-otel-collector:4317
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://0.0.0.0:5001"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=simpleauth;Username=postgres;Password=postgres"
    ports:
      - "5001:5001"
    networks:
      - signoz-ledger-net
      - ledger-net

  simple-auth-migrations:
    image: simple-auth
    entrypoint: ["dotnet", "SimpleAuth.MigrationsRunner.dll"]
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=simpleauth;Username=postgres;Password=postgres"
    networks:
      - ledger-net
    depends_on:
      postgres:
        condition: service_healthy

  user-api:
    image: user-api
    container_name: user-api
    depends_on:
      user-api-migrations:
        condition: service_started
      event-relay-worker:
        condition: service_healthy
    build:
      context: .
      dockerfile: UserApi/UserApi/Dockerfile
    environment:
      Kafka__FinancialAccountCreatedConsumer__BootstrapServers: broker:9092
      OpenTelemetry__ExporterUrl: http://signoz-otel-collector:4317
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:5002
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=userdb;Username=postgres;Password=postgres"
    ports:
      - "5002:5002"
    networks:
      - signoz-ledger-net
      - ledger-net

  user-api-migrations:
    image: user-api
    entrypoint: ["dotnet", "UserApi.MigrationsRunner.dll"]
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=userdb;Username=postgres;Password=postgres"
    networks:
      - ledger-net
    depends_on:
      postgres:
        condition: service_healthy

  financial-service:
    image: financial-service
    container_name: financial-service
    depends_on:
      event-relay-worker:
        condition: service_healthy
      financial-service-migrations:
        condition: service_started
    build:
      context: .
      dockerfile: FinancialService/FinancialService/Dockerfile
    environment:
      Kafka__FinancialAccountCreatedConsumer__BootstrapServers: broker:9092
      ASPNETCORE_Kestrel__Certificates__Default__Path: /app/certs/grpc-dev.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: 1234
      OpenTelemetry__ExporterUrl: http://signoz-otel-collector:4317
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:5003
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=financialservice;Username=postgres;Password=postgres"
    ports:
      - "5003:5003"
    volumes:
      - "./certs/grpc-dev.pfx:/app/certs/grpc-dev.pfx:ro"
    networks:
      - signoz-ledger-net
      - ledger-net

  financial-service-migrations:
    image: financial-service
    entrypoint: ["dotnet", "FinancialService.MigrationsRunner.dll"]
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=financialservice;Username=postgres;Password=postgres"
    networks:
      - ledger-net
    depends_on:
      postgres:
        condition: service_healthy

  ledger-gateway:
    image: ledger-gateway
    profiles: ["gateway"]
    container_name: ledger-gateway
    build:
      context: .
      dockerfile: LedgerGateway/LedgerGateway/Dockerfile
    environment:
      OpenTelemetry__ExporterUrl: http://signoz-otel-collector:4317
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:5000
    ports:
      - "5000:5000"
    volumes:
      - ./certs/grpc-dev.crt:/usr/local/share/ca-certificates/grp-dev.crt:ro
    command: |
      sh -c "
        update-ca-certificates &&
        dotnet LedgerGateway.dll
      "
    networks:
      - signoz-ledger-net
      - ledger-net

  broker:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:29092,PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:29092,PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/9092'"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
    ports:
      - "29092:29092"
    volumes:
      - ./Kafka/data/kafka:/var/lib/kafka/data
    networks:
      - signoz-ledger-net
      - ledger-net
      
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "broker:9092"
    networks:
      - ledger-net

    # open-telemetry-collector:
    #   image: otel/opentelemetry-collector-contrib:0.130.1
    #   containar_name: open-telemetry-collector
    #   restart: unless-stopped
    #   ports:
    #     - "4317:4317"
    #     - "4318:4318"
    #   volumes:
    #     - ./open-telemetry/config.yaml:/etc/otelcol-contrib/config.yaml
    #   networks:
    #     - ledger-net

    # signoz-otel-collector:
    #   image: signoz/signoz-otel-collector:latest
    #   containar_name: signoz
    #   restart: unless-stopped
    #   ports:
    #   networks:
    #     - ledger-net

volumes:
  user-data:

networks:
  ledger-net:
    driver: bridge
  signoz-ledger-net:
    external: true