apiVersion: v1
kind: ServiceAccount
metadata:
  name: ledger-waiter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ledger-waiter-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ledger-waiter-binding
subjects:
  - kind: ServiceAccount
    name: ledger-waiter
roleRef:
  kind: Role
  name: ledger-waiter-role
  apiGroup: rbac.authorization.k8s.io
