apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-service
  labels:
    app: financial-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financial-service
  template:
    metadata:
      labels:
        app: financial-service
    spec:
      serviceAccountName: ledger-waiter
      initContainers:
        - name: wait-for-migrations
          image: bitnami/kubectl:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for financial-service-migrations job to complete..."
              kubectl wait \
                --for=condition=complete \
                job/financial-service-migrations \
                --timeout=30s
        - name: wait-for-event-relay-worker
          image: bitnami/kubectl:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for event-relay-worker to be Ready..."
              kubectl wait \
                --for=condition=ready \
                pod -l app=event-relay-worker \
                --timeout=30s
      containers:
        - name: financial-service
          image: financial-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: Logging__LogLevel__Microsoft.AspNetCore
              value: Information
          envFrom:
            - configMapRef:
                name: financial-service
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

---

apiVersion: batch/v1
kind: Job
metadata:
  name: financial-service-migrations
spec:
  backoffLimit: 3
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for postgres..."
              until nc -z postgres 5432; do
                sleep 3
              done
              echo "Postgres is ready"
      restartPolicy: OnFailure
      containers:
        - name: financial-service-migrations
          image: financial-service
          command: ["dotnet", "FinancialService.MigrationsRunner.dll"]
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgres;Port=5432;Database=financialservice;Username=postgres;Password=postgres"

---

apiVersion: v1
kind: Service
metadata:
  name: financial-service
  labels:
    app: financial-service
spec:
  type: ClusterIP
  selector:
    app: financial-service
  ports:
    - name: http
      protocol: TCP
      port: 5003
      targetPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: financial-service
data:
  Kafka__FinancialAccountCreatedConsumer__BootstrapServers: "broker:9092"
  OpenTelemetry__ExporterUrl: "http://signoz-otel-collector:4317"
  ASPNETCORE_ENVIRONMENT: "Development"
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=financialservice;Username=postgres;Password=postgres"