apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-auth
  labels:
    app: simple-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-auth
  template:
    metadata:
      labels:
        app: simple-auth
    spec:
      serviceAccountName: ledger-waiter
      initContainers:
        - name: wait-for-migrations
          image: bitnami/kubectl:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for simple-auth-migrations job to complete..."
              kubectl wait \
                --for=condition=complete \
                job/simple-auth-migrations \
                --timeout=30s
        - name: wait-for-event-relay-worker
          image: bitnami/kubectl:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for event-relay-worker to be Ready..."
              kubectl wait \
                --for=condition=ready \
                pod -l app=event-relay-worker \
                --timeout=30s
      containers:
        - name: simple-auth
          image: simple-auth
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: Logging__LogLevel__Microsoft.AspNetCore
              value: Information
          envFrom:
            - configMapRef:
                name: simple-auth
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

---

apiVersion: batch/v1
kind: Job
metadata:
  name: simple-auth-migrations
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for postgres..."
              until nc -z postgres 5432; do
                sleep 3
              done
              echo "Postgres is ready"
      containers:
        - name: simple-auth-migrations
          image: simple-auth
          command: ["dotnet", "SimpleAuth.MigrationsRunner.dll"]
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgres;Port=5432;Database=simpleauth;Username=postgres;Password=postgres"

---

apiVersion: v1
kind: Service
metadata:
  name: simple-auth
  labels:
    app: simple-auth
spec:
  type: ClusterIP
  selector:
    app: simple-auth
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-auth
data:
  OpenTelemetry__ExporterUrl: http://signoz-otel-collector:4317
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=simpleauth;Username=postgres;Password=postgres"