services:
  postgres:
    image: postgres:16
    container_name: user-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - user-net

  user-api:
    image: user-api
    container_name: user-api
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: UserApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=userdb;Username=postgres;Password=postgres"
    ports:
      - "8080:8080"
    networks:
      - user-net

volumes:
  user-data:

networks:
  user-net: